
services:
  mssql:
    container_name: mssql
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: localhost
    ports:
      - "1433:1433"
    environment:
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "P@ssw0rd@powergym"
      ACCEPT_EULA: "Y"
      MSSQL_ENCRYPT: "false"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/mssql/backups:/var/opt/mssql/backups
      - ./data/mssql/data:/var/opt/mssql/data
      - ./data/mssql/log:/var/opt/mssql/log
